version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Test
          workspace: Gridicons.xcworkspace
          scheme: Gridicons
          device: iPhone XS
          ios-version: "12.1"
          bundle-install: false
          pod-install: false
      - ios/validate-podspec:
          name: Validate Podspec
          podspec-path: Gridicons.podspec
          bundle-install: true
