# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: mac

env:
  IMAGE_ID: xcode-16.4

common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0

# This is the default pipeline – it will build and test the app
steps:
  ########################
  # Validate Swift Package
  ########################
  - label: "🔬 Validating Swift Package"
    key: "test"
    command: ".buildkite/validate_swift_package"
    plugins: *common_plugins
